// Code generated by cod; DO NOT EDIT.
package particle

import (
	"github.com/unitoftime/ecs"
)

var ColorComp = ecs.NewComp[Color]()

func (c Color) CompId() ecs.CompId {
	return ColorComp.CompId()
}

func (c Color) CompWrite(w ecs.W) {
	ColorComp.WriteVal(w, c)
}

var SizeComp = ecs.NewComp[Size]()

func (c Size) CompId() ecs.CompId {
	return SizeComp.CompId()
}

func (c Size) CompWrite(w ecs.W) {
	SizeComp.WriteVal(w, c)
}
